name: "sitkoru/github-deployment-action"
description: "Action to manage GitHub Deployments"
branding:
  icon: "package"
  color: "blue"

inputs:
  action: 
    description: "Deployment action"
    required: true
    default: "create"
  version:
    description: "Service version"
    required: false
  token:
    description: "Github token"
    required: true
  environment:
    description: "Github environment"
    required: false
    default: "production"
  ref:
    description: "Github ref"
    required: false
  deployment_id:
    description: "Github deployment id"
    required: false
  state:
    description: "Github deployment state"
    required: false

runs:
  using: "composite"
  steps:
    - uses: chrnorm/deployment-status@releases/v1
      if: ${{ inputs.action == 'create' }}
      with:
        description: ${{ inputs.version }}
        token: ${{ inputs.token }}
        environment: ${{ inputs.environment }}
        ref: ${{ inputs.ref }}
    - uses: chrnorm/deployment-status@releases/v1
      if: ${{ inputs.action == 'update' }}
      with:
        token: ${{ inputs.token }}
        state: ${{ inputs.state }}
        deployment_id: ${{ inputs.deployment_id }}